version: '3.8'
services:
  db:
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    
  dwh:
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=dwh
      - POSTGRES_PASSWORD=dwh
    ports:
      - '5434:5432'
    volumes: 
      - dwh:/var/lib/postgresql/data

  app:
    build:
      context: app/
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    depends_on:
      - db
      - dwh


volumes:
  db:
    driver: local
  dwh:
    driver: local